{% set python_min = "3.8" %}
{% set name = "fastclasses-json" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4f06cd559a4e752e31c0ae04622d1c7abb5a66fa53b550c262d6de49082225a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - fastclasses_json
  commands:
    - pip check
    - pytest
  source_files:
    - .
  requires:
    - pip
    - python {{ python_min }}
    - pytest

about:
  home: https://github.com/cakemanny/fastclasses-json
  summary: Quickly serialize dataclasses to and from JSON
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - julian-belina
